name: My Workflow
on:
  pull_request:
    types: [opened]
jobs:
  comment: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pull conftest container image
        run: |
          docker pull openpolicyagent/conftest:latest 
      - name: run bash and conftest
        run: |
          echo "printing some lines, going to print directory..."
          ls aws
          echo $PWD
          docker run --rm -v $PWD:/project -w /project openpolicyagent/conftest:latest test aws/ -p policies/ aws/
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'thanks for reporting!'
            })
