name: My Workflow
on:
  pull_request:
    types: [opened]
jobs:
  comment: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pull conftest container image
        run: |
          docker pull openpolicyagent/conftest:latest 
      - name: run conftest
        id: conftest
        run: |
          docker run --rm -v $PWD:/project -w /project openpolicyagent/conftest:latest test aws/ -p policies/ aws/
          test='hello'
          echo "testing=$test" >> $GITHUB_OUTPUT
      - name: print conftest output
        if: always()
        run: |
          echo 'outcome - ${{ steps.conftest.outcome }}'
          echo 'outputs - ${{ steps.conftest.outputs }}'
          echo 'out- ${{ steps.conftest.outputs.stdout }}'
          echo 'err- ${{ steps.conftest.outputs.stderr }}'
          echo "test - ${{ steps.conftest.outputs.testing }}'
      - uses: actions/github-script@v6
        if: always()
        with:
          script: |
            const output = `output: ${{ steps.conftest.outputs.stdout }} and ${{ steps.conftest.outputs.stderr }}`
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
