name: My Workflow
on:
  pull_request:
    types: [opened]
jobs:
  comment: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pull conftest container image
        run: |
          docker pull openpolicyagent/conftest:latest 
      - name: run conftest
        id: conftest
        run: |
          echo "hello ?" && echo "this aerrpr" >&2
#          docker run --rm -v $PWD:/project -w /project openpolicyagent/conftest:latest test aws/ -p policies/ aws/ > conftest-result.txt
      - name: print conftest output
        if: always()
        run: |
          echo 'outcome - ${{ steps.conftest.outcome }}'
          echo 'out- ${{ steps.conftest.stdout }}'
          echo 'err- ${{ steps.conftest.stderr }}'
          echo 'out2- ${{ steps.conftest.outputs.stdout }}'
          echo 'err2- ${{ steps.conftest.outputs.stderr }}'
          echo 'end'
      - uses: actions/github-script@v6
#         if: always()
        with:
          script: |
            const output = "$(cat conftest-result.txt)"
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
