name: My Workflow
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  comment: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: print the tfplan.json file 
        run: |
          cat tfplan.json
