name: My Workflow
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  comment: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: latest
      - name: run opa
        id: opa
        run: |
          opa eval --data policies/tag-policy.rego --input aws/tfplan.json "data.main" --format=pretty > opa-result.json
      - name: print result into github output
        if: always()
        id: opa-result
        run: |
          output="$(jq -c . opa-result.json)"
          echo "result=${output}" >> "${GITHUB_OUTPUT}"
          # delimiter="$(openssl rand -hex 8)"
          # echo "result<<${delimiter}" >> "${GITHUB_OUTPUT}"
          # echo "$(cat conftest-result.txt)" >> "${GITHUB_OUTPUT}"
          # echo "${delimiter}" >> "${GITHUB_OUTPUT}"
      - uses: actions/github-script@v6
        if: always()
        with:
          script: |
            const colorRegex = /\u001b\[\d{1,2}m/g;
            let color = { "deny": "+ ", "warn": "!" };
            let raw = ${{ steps.opa-result.outputs.result }};
            deny = raw.deny.map(x => `${color.deny}${x}`)
            console.log(deny)
            let output = `### open policy agent check: \`${{ steps.opa.outcome }}\`
            <details><summary>policy check output</summary>
            
            \`\`\`\n
            ${{ steps.opa-result.outputs.result }}
            \`\`\`
            </details>
            
            end`
            
            output = output.replace('"', '\"')
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
