name: My Workflow
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  comment: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: checkout aws policy repo
        uses: actions/checkout@v3
        with:
          repository: ricky-deriv/aws-policy
          ref: main
          path: external
      - name: archive terraform json plan
        uses: actions/upload-artifact@v3
        with:
          name: tf-plan
          path: aws/tfplan.json
          retention-days: 5
      - uses: open-policy-agent/setup-opa@v2
      - name: run opa
        id: opa
        run: |
          opa eval -b ${{ github.workspace }}/external/ --input aws/tfplan.json "data.main" --format=pretty > opa-result.json
      - name: print result into github output
        if: always()
        id: opa-result
        run: |
          output="$(jq -c . opa-result.json)"
          echo "result=${output}" >> "${GITHUB_OUTPUT}"
          ls
      - uses: actions/github-script@v6
        if: always()
        with:
          script: |
            const result = ${{ steps.opa-result.outputs.result }}
            const colors = {"warn":"!", "deny":"-"};
            const deny = result.deny.map(x => `${colors.deny} ${x}`);
            const warn = result.warn.map(x => `${colors.warn} ${x}`); 
            const outcome = deny.length > 0 ? 'Failure' : 'Success';
            let output = `### open policy agent check: \`${outcome}\`
            <details><summary>policy check output</summary>
            
            \`\`\`diff\n
            Deny: ${deny.length}
            ${deny.join("\n")}
            
            # Warn ${warn.length}
            ${warn.join("\n")}
            \`\`\`
            </details>
            
            end`
            
            output = output.replace('"', '\"')
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
  call-reusable:
    needs: comment
    uses: ./.github/workflows/opa.yml
  display-output:
    needs: call-reusable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  
      - name: check-dir
        run: |
          pwd
          ls
      - name: get opa-results
        uses: actions/download-artifact@v3
        with:
          name: opa-result
      - name: check-if-opa-result
        run: |
          pwd
          ls
