name: My Workflow
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  comment: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: latest
      - name: run opa
        id: conftest
        run: |
          opa eval --data policies/tag-policy.rego --input aws/tfplan.json "data.main" > conftest-result.txt
      - name: print result into github output
        if: always()
        id: conftest-result
        run: |
          delimiter="$(openssl rand -hex 8)"
          echo "result<<${delimiter}" >> "${GITHUB_OUTPUT}"
          echo "$(cat conftest-result.txt)" >> "${GITHUB_OUTPUT}"
          echo "${delimiter}" >> "${GITHUB_OUTPUT}"
      - uses: actions/github-script@v6
        if: always()
        with:
          script: |
            const colorRegex = /\u001b\[\d{1,2}m/g;
            let output = `### open policy agent check: \`${{ steps.conftest.outcome }}\`
            <details><summary>policy check output</summary>
            
            \`\`\`\n
            ${{ steps.conftest-result.outputs.result }}
            \`\`\`
            </details>
            
            end`
            
            output = output.replace(colorRegex, "")
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
