name: My Workflow
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  initialize:
    name: "get dirs"
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          echo matrix="$(jq -Mc -n '{"dir":["aws","project"]}')" >>$GITHUB_OUTPUT
          #
  terraform: 
    needs: initialize
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.initialize.outputs.matrix)}}
    outputs:
      plan-json: ${{ steps.opa-result.outputs.opa-result }}
    steps:
      - uses: actions/checkout@v3
      - name: archive terraform json plan
        uses: actions/upload-artifact@v3
        with:
          name: tf-plan
          path: aws/tfplan.json
          retention-days: 5
      - name: test-matrix
        run: |
          echo "testing matrix"
          echo "dir: ${{ matrix.dir }}"
      - name: testing sec
        run: |
          echo "sec ${{ secrets.AWS_POLICY_REPO_TOKEN }}"
      - name: print result into github output
        if: always()
        id: opa-result
        working-directory: ${{ matrix.dir }}
        run: |
          ls
          output="$(jq -c . tfplan.json)"
          echo "opa-result=${output}" >> "${GITHUB_OUTPUT}"
  opa-eval:
    needs: [ terraform, initialize ]
    strategy:
      matrix: ${{fromJson(needs.initialize.outputs.matrix)}}
    uses: ./.github/workflows/opa.yml
    with: 
      tfplan: ${{ needs.terraform.outputs.plan-json }}
      dir: ${{ matrix.dir }}
  display-output:
    needs: [ initialize, opa-eval ]
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.initialize.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v3  
      - name: name artifacts
        working-directory: ${{ matrix.dir }}
        run: |
          new_name=$(echo ${{ matrix.dir }} | tr '/' ' ')
          echo "artifact-name=${new_name}" >> "${GITHUB_ENV}"
      - name: get opa-results
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.artifact-name }}-opa-result
      - name: print result into github output
        if: always()
        id: opa-result
        run: |
          pwd
          echo "next ls current.."
          ls
          output="$(jq -c . opa-result.json)"
          echo "result=${output}" >> "${GITHUB_OUTPUT}"
          cat opa-result.json
      - uses: actions/github-script@v6
        if: always()
        with:
          script: |
            const result = ${{ steps.opa-result.outputs.result }}
            const colors = {"warn":"!", "deny":"-"};
            const deny = result.deny.map(x => `${colors.deny} ${x}`);
            const warn = result.warn.map(x => `${colors.warn} ${x}`); 
            const outcome = deny.length > 0 ? 'Failure' : 'Success';
            let output = `### open policy agent check: \`${outcome}\`
            Directory: \`${{ matrix.dir }}\`
            <details><summary>policy check output</summary>
            
            \`\`\`diff\n
            Deny: ${deny.length}
            ${deny.join("\n")}
            
            # Warn ${warn.length}
            ${warn.join("\n")}
            \`\`\`
            </details>
            
            end`
            
            output = output.replace('"', '\"')
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
