name: My Workflow
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  comment: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: latest
      - name: run opa
        id: opa
        run: |
          opa eval -b policies/ --input aws/tfplan.json "data.main" --format=pretty > opa-result.json
      - name: print result into github output
        if: always()
        id: opa-result
        run: |
          output="$(jq -c . opa-result.json)"
          echo "result=${output}" >> "${GITHUB_OUTPUT}"
          # delimiter="$(openssl rand -hex 8)"
          # echo "result<<${delimiter}" >> "${GITHUB_OUTPUT}"
          # echo "$(cat conftest-result.txt)" >> "${GITHUB_OUTPUT}"
          # echo "${delimiter}" >> "${GITHUB_OUTPUT}"
      - uses: actions/github-script@v6
        if: always()
        with:
          script: |
            const result = ${{ steps.opa-result.outputs.result }}
            let output = `### open policy agent check: \`${{ steps.opa.outcome }}\`
            <details><summary>policy check output</summary>
            
            \`\`\`\n
            # Deny
            ${result.deny.join("\n")}
            # Warn
            ${result.warn.join("\n")}
            \`\`\`
            </details>
            
            end`
            
            output = output.replace('"', '\"')
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
