name: My Workflow
on:
  pull_request:
    types: [opened]
jobs:
  comment: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pull conftest container image
        run: |
          docker pull openpolicyagent/conftest:latest 
      - name: run conftest
        id: conftest
        run: |
          test='hello'
          echo "testing=$test" >> $GITHUB_OUTPUT 
          docker run --rm -v $PWD:/project -w /project openpolicyagent/conftest:latest test aws/ -p policies/ aws/ > conftest-result.txt
      - name: get conftest result file content
        if: always()
        run: |
          RESULT=$(cat conftest=result.txt)
          echo "conftest_result=$RESULT" >> $GITHUB_OUTPUT
      - name: print conftest output
        if: always()
        run: |
          ls
          cat conftest-result.txt
          echo 'outcome - ${{ steps.conftest.outcome }}'
          echo 'outputs - ${{ steps.conftest.outputs }}'
          echo 'out- ${{ steps.conftest.outputs.stdout }}'
          echo 'err- ${{ steps.conftest.outputs.stderr }}'
          echo 'file - ${{ steps.conftest.outputs.conftest_result }}'
      - uses: actions/github-script@v6
        if: always()
        with:
          script: |
            const output = "$(cat conftest-result.txt)"
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
