name: My Workflow
on:
  pull_request:
    types: [opened]
jobs:
  comment: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pull conftest container image
        run: |
          docker pull openpolicyagent/conftest:latest 
      - name: run conftest
        id: conftest
        run: |
          docker run --rm -v $PWD:/project -w /project openpolicyagent/conftest:latest test aws/ -p policies/ aws/ -O result.txt
      - uses: actions/github-script@v6
        if: always()
        with:
          script: |
            const output = `output: ${{ steps.conftest.outputs.stdout }} and ${{ steps.conftest.outputs.stderr }}`
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
