name: My Workflow
on:
  push:
    branches: 
      - main
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - name: comment pr
      uses: actions/github-script@v6
      if: always()
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: 'Hello world!'
          })
