name: My Workflow
on:
  push:
    branches: 
      - main
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        echo "Hello World"
