name: comment on pull request
on: 
  pull_request:
    types: [opened, synchronize]
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: output comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          body: |
            Hello! thanks for opening a PR. will get back soon!
          token: ${{ secrets.GITHUB_TOKEN }}
