name: OPA
on: 
  workflow_run:
    workflows: ["first-workflow"]
    types: 
      - completed
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "hello from different workflow"
    
