name: Policy evaluation workflow

on:
  workflow_call:
jobs:
  echo-result:
    runs-on: ubuntu-latest
    steps:
    - name: test-echo
      run: |
        echo "hello from reusable workflow"
    - name: get-artifact
      uses: actions/download-artifact@v3
      with:
        name: tf-plan
    - name: test
      run: |
        ls
        echo "end"
