name: Policy evaluation workflow

on:
  workflow_call:
    inputs:
      dir:
        required: true
        type: string
      
jobs:
  echo-result:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup SSH Keys and known_hosts
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        mkdir -p /home/runner/.ssh
        echo "${{ secrets.POLICY_PRIVATE_KEY }}" > /home/runner/.ssh/github_actions
        chmod 600 /home/runner/.ssh/github_actions
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add /home/runner/.ssh/github_actions
    - name: test
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run:
        git clone git@github.com:ricky-deriv/aws-policy.git
        ls 
    - name: checkout aws policy repo
      uses: actions/checkout@v3
      with:
        repository: ricky-deriv/aws-policy
        ref: main
        path: external
        token: ${{ secrets.AWS_POLICY_REPO_TOKEN }}
    - name: edit dir name for artifact
      run: |
        new_name=$(echo ${{ inputs.dir }} | tr '/' ' ')
        echo "artifact-name=${new_name}" >> "${GITHUB_ENV}"
    - name: get tf-results
      uses: actions/download-artifact@v3
      with:
        name: ${{ env.artifact-name }}-tf-plan
    - uses: open-policy-agent/setup-opa@v2
    - name: run opa
      id: opa
      working-directory: ${{ inputs.dir }}
      run: |
        opa eval -b ${{ github.workspace }}/external/ --input tfplan.json "data.main" --format=pretty > opa-result.json
    - name: edit dir name for artifact
      run: |
        new_name=$(echo ${{ inputs.dir }} | tr '/' ' ')
        echo "artifact-name=${new_name}" >> "${GITHUB_ENV}"
    - name: upload opa result
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.artifact-name }}-opa-result
        path: ${{ inputs.dir }}/opa-result.json