name: Policy evaluation workflow

on:
  workflow_call:
    inputs:
      opa-result:
        required: true
        type: string
jobs:
  echo-result:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: checkout aws policy repo
      uses: actions/checkout@v3
      with:
        repository: ricky-deriv/aws-policy
        ref: main
        path: external
    - name: test-echo
      run: |
        echo "hello from reusable workflow"
    - name: get-artifact
      uses: actions/download-artifact@v3
      with:
        name: tf-plan
    - name: test
      run: |
        ls
        echo "end"
    - uses: open-policy-agent/setup-opa@v2
    - name: run opa
      id: opa
      run: |
        echo "print github-output into plan file"
        echo "${{ inputs.opa-result }}" > aws/new-tfplan.json
        echo "cat the new file in aws..."
        ls aws
        cat aws/new-tfplan.json
        opa eval -b ${{ github.workspace }}/external/ --input aws/new-tfplan.json "data.main" --format=pretty > opa-result.json
    - name: upload opa result
      uses: actions/upload-artifact@v3
      with:
        name: opa-result
        path: opa-result.json
